2023-03-21 11:12:55 - INFO  - UPDATE submit SET status='TESTING' WHERE submitId='s_20230321111251_20230307123639'
2023-03-21 11:13:04 - INFO  - UPDATE submit SET status='SUCCESS', score=39.58, testTime='2023-03-21 11:12:55', resultLink='https://resource.onsite.run/results/2023031601/20230307123639&2023-03-21_11-12-51.zip' WHERE submitId='s_20230321111251_20230307123639'
2023-03-21 11:15:40 - INFO  - UPDATE submit SET status='TESTING' WHERE submitId='s_20230321111538_20230307123639'
2023-03-21 11:15:49 - INFO  - UPDATE submit SET status='SUCCESS', score=39.58, testTime='2023-03-21 11:15:40', resultLink='https://resource.onsite.run/results/2023031601/20230307123639&2023-03-21_11-15-38.zip' WHERE submitId='s_20230321111538_20230307123639'
2023-03-21 11:18:01 - INFO  - UPDATE submit SET status='TESTING' WHERE submitId='s_20230321111758_20230307123639'
2023-03-21 11:18:05 - INFO  - UPDATE submit SET status='PULL ERROR', score=NULL, testTime='2023-03-21 11:18:01', resultLink='https://resource.onsite.run/results/2023031601/20230307123639&2023-03-21_11-17-58.zip' WHERE submitId='s_20230321111758_20230307123639'
2023-03-21 11:23:24 - INFO  - UPDATE submit SET status='TESTING' WHERE submitId='s_20230321112324_20230307123639'
2023-03-21 11:23:36 - INFO  - UPDATE submit SET status='PULL ERROR', score=NULL, testTime='2023-03-21 11:23:24', resultLink='https://resource.onsite.run/results/2023031601/20230307123639&2023-03-21_11-23-24.zip' WHERE submitId='s_20230321112324_20230307123639'
2023-03-21 11:26:51 - INFO  - UPDATE submit SET status='TESTING' WHERE submitId='s_20230321112647_20230307123639'
2023-03-21 11:26:54 - INFO  - UPDATE submit SET status='CONTAINER ERROR', score=NULL, testTime='2023-03-21 11:26:51', resultLink='https://resource.onsite.run/results/2023031601/20230307123639&2023-03-21_11-26-48.zip' WHERE submitId='s_20230321112647_20230307123639'
2023-03-21 11:28:41 - INFO  - UPDATE submit SET status='TESTING' WHERE submitId='s_20230321112839_20230307123639'
2023-03-21 11:28:48 - INFO  - UPDATE submit SET status='EVALUATE ERROR', score=NULL, testTime='2023-03-21 11:28:41', resultLink='https://resource.onsite.run/results/2023031601/20230307123639&2023-03-21_11-28-39.zip' WHERE submitId='s_20230321112839_20230307123639'
2023-03-21 11:32:26 - INFO  - UPDATE submit SET status='TESTING' WHERE submitId='s_20230321113222_20230307123639'
2023-03-21 11:32:29 - INFO  - UPDATE submit SET status='CONTAINER ERROR', score=NULL, testTime='2023-03-21 11:32:26', resultLink='https://resource.onsite.run/results/2023031601/20230307123639&2023-03-21_11-32-23.zip' WHERE submitId='s_20230321113222_20230307123639'
2023-03-21 11:39:07 - INFO  - UPDATE submit SET status='TESTING' WHERE submitId='s_20230321113902_20230307123639'
2023-03-21 11:39:15 - INFO  - UPDATE submit SET status='UPLOAD ERROR', score=39.58, testTime='2023-03-21 11:39:07', resultLink=NULL WHERE submitId='s_20230321113902_20230307123639'
2023-03-21 11:39:55 - INFO  - UPDATE submit SET status='TESTING' WHERE submitId='s_20230321113950_20230307123639'
2023-03-21 11:40:03 - INFO  - UPDATE submit SET status='SUCCESS', score=39.74, testTime='2023-03-21 11:39:55', resultLink='https://resource.onsite.run/results/2023031601/20230307123639&2023-03-21_11-39-51.zip' WHERE submitId='s_20230321113950_20230307123639'
2023-03-21 11:40:05 - INFO  - UPDATE submit SET status='TESTING' WHERE submitId='s_20230321114003_20230307123639'
2023-03-21 11:40:22 - INFO  - UPDATE submit SET status='SUCCESS', score=35.0, testTime='2023-03-21 11:40:05', resultLink='https://resource.onsite.run/results/2023031601/20230307123639&2023-03-21_11-40-03.zip' WHERE submitId='s_20230321114003_20230307123639'
2023-03-24 13:42:44 - INFO  - UPDATE submit SET status='TESTING', testTime=2023-03-24 13:42:44.695023 WHERE submitId='s_20230322122024_20230307123639'
2023-03-24 13:42:44 - ERROR - UPDATE submit SET status='TESTING', testTime=2023-03-24 13:42:44.695023 WHERE submitId='s_20230322122024_20230307123639'
Traceback (most recent call last):
  File "/home/ubuntu/onsite-develop/onsite-test-server/tester/connector.py", line 100, in _db_commit
    cur.execute(script)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 606, in tough_method
    result = method(*args, **kwargs)  # try to execute
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '13:42:44.695023 WHERE submitId='s_20230322122024_20230307123639'' at line 1")
2023-03-24 13:42:49 - INFO  - UPDATE submit SET status='PULL ERROR', score=NULL, resultLink='https://resource.onsite.run/results/2023031601/20230307123639&2023-03-22_00-20-25.zip' WHERE submitId='s_20230322122024_20230307123639'
2023-03-25 02:12:25 - INFO  - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:25.481918 WHERE submitId='s_20230323053101_20230323043922'
2023-03-25 02:12:25 - INFO  - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:25.482593 WHERE submitId='s_20230323053111_20230323043922'
2023-03-25 02:12:25 - INFO  - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:25.483165 WHERE submitId='s_20230323053119_20230323043922'
2023-03-25 02:12:25 - INFO  - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:25.483258 WHERE submitId='s_20230323053128_20230323043922'
2023-03-25 02:12:25 - INFO  - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:25.483331 WHERE submitId='s_20230323053221_20230323044004'
2023-03-25 02:12:25 - INFO  - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:25.483460 WHERE submitId='s_20230323053230_20230323044004'
2023-03-25 02:12:25 - INFO  - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:25.483947 WHERE submitId='s_20230323053238_20230323044004'
2023-03-25 02:12:25 - INFO  - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:25.484152 WHERE submitId='s_20230323053245_20230323044004'
2023-03-25 02:12:25 - ERROR - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:25.481918 WHERE submitId='s_20230323053101_20230323043922'
Traceback (most recent call last):
  File "/home/ubuntu/onsite-develop/onsite-test-server/tester/connector.py", line 101, in _db_commit
    conn.commit()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 426, in commit
    self._con.commit()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 470, in commit
    self._read_ok_packet()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 443, in _read_ok_packet
    pkt = self._read_packet()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '02:12:25.483947 WHERE submitId='s_20230323053238_20230323044004'' at line 1")
2023-03-25 02:12:25 - ERROR - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:25.484152 WHERE submitId='s_20230323053245_20230323044004'
Traceback (most recent call last):
  File "/home/ubuntu/onsite-develop/onsite-test-server/tester/connector.py", line 100, in _db_commit
    cur.execute(script)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 606, in tough_method
    result = method(*args, **kwargs)  # try to execute
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '02:12:25.481918 WHERE submitId='s_20230323053101_20230323043922'' at line 1")
2023-03-25 02:12:25 - ERROR - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:25.483258 WHERE submitId='s_20230323053128_20230323043922'
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 606, in tough_method
    result = method(*args, **kwargs)  # try to execute
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
pymysql.err.InterfaceError: (0, '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/onsite-develop/onsite-test-server/tester/connector.py", line 100, in _db_commit
    cur.execute(script)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 675, in tough_method
    raise error2  # raise the other error
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 657, in tough_method
    result = method2(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '02:12:25.483258 WHERE submitId='s_20230323053128_20230323043922'' at line 1")
2023-03-25 02:12:25 - ERROR - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:25.482593 WHERE submitId='s_20230323053111_20230323043922'
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 606, in tough_method
    result = method(*args, **kwargs)  # try to execute
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
pymysql.err.InterfaceError: (0, '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/onsite-develop/onsite-test-server/tester/connector.py", line 100, in _db_commit
    cur.execute(script)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 675, in tough_method
    raise error2  # raise the other error
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 657, in tough_method
    result = method2(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '02:12:25.482593 WHERE submitId='s_20230323053111_20230323043922'' at line 1")
2023-03-25 02:12:30 - INFO  - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:30.523303 WHERE submitId='s_20230323053101_20230323043922'
2023-03-25 02:12:30 - INFO  - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:30.523630 WHERE submitId='s_20230323053111_20230323043922'
2023-03-25 02:12:30 - INFO  - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:30.524408 WHERE submitId='s_20230323053119_20230323043922'
2023-03-25 02:12:30 - INFO  - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:30.524621 WHERE submitId='s_20230323053221_20230323044004'
2023-03-25 02:12:30 - INFO  - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:30.524704 WHERE submitId='s_20230323053230_20230323044004'
2023-03-25 02:12:30 - INFO  - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:30.524519 WHERE submitId='s_20230323053128_20230323043922'
2023-03-25 02:12:30 - INFO  - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:30.526046 WHERE submitId='s_20230323053238_20230323044004'
2023-03-25 02:12:30 - INFO  - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:30.526092 WHERE submitId='s_20230323053245_20230323044004'
2023-03-25 02:12:30 - ERROR - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:30.524704 WHERE submitId='s_20230323053230_20230323044004'
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 606, in tough_method
    result = method(*args, **kwargs)  # try to execute
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
pymysql.err.InterfaceError: (0, '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/onsite-develop/onsite-test-server/tester/connector.py", line 100, in _db_commit
    cur.execute(script)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 675, in tough_method
    raise error2  # raise the other error
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 657, in tough_method
    result = method2(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '02:12:30.524704 WHERE submitId='s_20230323053230_20230323044004'' at line 1")
2023-03-25 02:12:30 - ERROR - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:30.526046 WHERE submitId='s_20230323053238_20230323044004'
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 606, in tough_method
    result = method(*args, **kwargs)  # try to execute
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
pymysql.err.InterfaceError: (0, '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/onsite-develop/onsite-test-server/tester/connector.py", line 100, in _db_commit
    cur.execute(script)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 675, in tough_method
    raise error2  # raise the other error
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 657, in tough_method
    result = method2(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '02:12:30.526046 WHERE submitId='s_20230323053238_20230323044004'' at line 1")
2023-03-25 02:12:30 - ERROR - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:30.523630 WHERE submitId='s_20230323053111_20230323043922'
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 606, in tough_method
    result = method(*args, **kwargs)  # try to execute
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
pymysql.err.InterfaceError: (0, '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/onsite-develop/onsite-test-server/tester/connector.py", line 100, in _db_commit
    cur.execute(script)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 675, in tough_method
    raise error2  # raise the other error
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 657, in tough_method
    result = method2(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '02:12:30.523630 WHERE submitId='s_20230323053111_20230323043922'' at line 1")
2023-03-25 02:12:30 - ERROR - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:30.524519 WHERE submitId='s_20230323053128_20230323043922'
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 606, in tough_method
    result = method(*args, **kwargs)  # try to execute
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
pymysql.err.InterfaceError: (0, '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/onsite-develop/onsite-test-server/tester/connector.py", line 100, in _db_commit
    cur.execute(script)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 675, in tough_method
    raise error2  # raise the other error
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 657, in tough_method
    result = method2(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '02:12:30.524519 WHERE submitId='s_20230323053128_20230323043922'' at line 1")
2023-03-25 02:12:30 - ERROR - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:30.523303 WHERE submitId='s_20230323053101_20230323043922'
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 606, in tough_method
    result = method(*args, **kwargs)  # try to execute
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
pymysql.err.InterfaceError: (0, '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/onsite-develop/onsite-test-server/tester/connector.py", line 100, in _db_commit
    cur.execute(script)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 675, in tough_method
    raise error2  # raise the other error
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 657, in tough_method
    result = method2(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '02:12:30.523303 WHERE submitId='s_20230323053101_20230323043922'' at line 1")
2023-03-25 02:12:30 - ERROR - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:30.524621 WHERE submitId='s_20230323053221_20230323044004'
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 606, in tough_method
    result = method(*args, **kwargs)  # try to execute
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
pymysql.err.InterfaceError: (0, '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/onsite-develop/onsite-test-server/tester/connector.py", line 100, in _db_commit
    cur.execute(script)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 675, in tough_method
    raise error2  # raise the other error
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 657, in tough_method
    result = method2(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '02:12:30.524621 WHERE submitId='s_20230323053221_20230323044004'' at line 1")
2023-03-25 02:12:30 - ERROR - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:30.526092 WHERE submitId='s_20230323053245_20230323044004'
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 606, in tough_method
    result = method(*args, **kwargs)  # try to execute
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
pymysql.err.InterfaceError: (0, '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/onsite-develop/onsite-test-server/tester/connector.py", line 100, in _db_commit
    cur.execute(script)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 675, in tough_method
    raise error2  # raise the other error
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 657, in tough_method
    result = method2(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '02:12:30.526092 WHERE submitId='s_20230323053245_20230323044004'' at line 1")
2023-03-25 02:12:30 - ERROR - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:30.524408 WHERE submitId='s_20230323053119_20230323043922'
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 606, in tough_method
    result = method(*args, **kwargs)  # try to execute
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
pymysql.err.InterfaceError: (0, '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/onsite-develop/onsite-test-server/tester/connector.py", line 100, in _db_commit
    cur.execute(script)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 675, in tough_method
    raise error2  # raise the other error
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 657, in tough_method
    result = method2(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '02:12:30.524408 WHERE submitId='s_20230323053119_20230323043922'' at line 1")
2023-03-25 02:12:33 - INFO  - UPDATE submit SET status='CONTAINER ERROR', score=NULL, resultLink='https://resource.onsite.run/results/2023031902/20230323044004&2023-03-23_17-32-38.zip' WHERE submitId='s_20230323053238_20230323044004'
2023-03-25 02:12:34 - INFO  - UPDATE submit SET status='CONTAINER ERROR', score=NULL, resultLink='https://resource.onsite.run/results/2023031903/20230323043922&2023-03-23_17-31-29.zip' WHERE submitId='s_20230323053128_20230323043922'
2023-03-25 02:12:34 - INFO  - UPDATE submit SET status='CONTAINER ERROR', score=NULL, resultLink='https://resource.onsite.run/results/2023031405/20230323043922&2023-03-23_17-31-01.zip' WHERE submitId='s_20230323053101_20230323043922'
2023-03-25 02:12:34 - INFO  - UPDATE submit SET status='CONTAINER ERROR', score=NULL, resultLink='https://resource.onsite.run/results/2023031405/20230323044004&2023-03-23_17-32-22.zip' WHERE submitId='s_20230323053221_20230323044004'
2023-03-25 02:12:34 - INFO  - UPDATE submit SET status='CONTAINER ERROR', score=NULL, resultLink='https://resource.onsite.run/results/2023031903/20230323044004&2023-03-23_17-32-46.zip' WHERE submitId='s_20230323053245_20230323044004'
2023-03-25 02:12:35 - INFO  - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:35.541447 WHERE submitId='s_20230323053111_20230323043922'
2023-03-25 02:12:35 - INFO  - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:35.541540 WHERE submitId='s_20230323053119_20230323043922'
2023-03-25 02:12:35 - INFO  - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:35.541872 WHERE submitId='s_20230323053230_20230323044004'
2023-03-25 02:12:35 - ERROR - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:35.541540 WHERE submitId='s_20230323053119_20230323043922'
Traceback (most recent call last):
  File "/home/ubuntu/onsite-develop/onsite-test-server/tester/connector.py", line 100, in _db_commit
    cur.execute(script)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 606, in tough_method
    result = method(*args, **kwargs)  # try to execute
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '02:12:35.541540 WHERE submitId='s_20230323053119_20230323043922'' at line 1")
2023-03-25 02:12:35 - ERROR - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:35.541872 WHERE submitId='s_20230323053230_20230323044004'
Traceback (most recent call last):
  File "/home/ubuntu/onsite-develop/onsite-test-server/tester/connector.py", line 100, in _db_commit
    cur.execute(script)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 606, in tough_method
    result = method(*args, **kwargs)  # try to execute
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '02:12:35.541872 WHERE submitId='s_20230323053230_20230323044004'' at line 1")
2023-03-25 02:12:35 - ERROR - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:35.541447 WHERE submitId='s_20230323053111_20230323043922'
Traceback (most recent call last):
  File "/home/ubuntu/onsite-develop/onsite-test-server/tester/connector.py", line 100, in _db_commit
    cur.execute(script)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 606, in tough_method
    result = method(*args, **kwargs)  # try to execute
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '02:12:35.541447 WHERE submitId='s_20230323053111_20230323043922'' at line 1")
2023-03-25 02:12:36 - INFO  - UPDATE submit SET status='CONTAINER ERROR', score=NULL, resultLink='https://resource.onsite.run/results/2023031902/20230323043922&2023-03-23_17-31-20.zip' WHERE submitId='s_20230323053119_20230323043922'
2023-03-25 02:12:36 - INFO  - UPDATE submit SET status='CONTAINER ERROR', score=NULL, resultLink=NULL WHERE submitId='s_20230323053119_20230323043922'
2023-03-25 02:12:40 - INFO  - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:40.557238 WHERE submitId='s_20230323053111_20230323043922'
2023-03-25 02:12:40 - INFO  - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:40.557442 WHERE submitId='s_20230323053230_20230323044004'
2023-03-25 02:12:40 - ERROR - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:40.557442 WHERE submitId='s_20230323053230_20230323044004'
Traceback (most recent call last):
  File "/home/ubuntu/onsite-develop/onsite-test-server/tester/connector.py", line 100, in _db_commit
    cur.execute(script)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 606, in tough_method
    result = method(*args, **kwargs)  # try to execute
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '02:12:40.557442 WHERE submitId='s_20230323053230_20230323044004'' at line 1")
2023-03-25 02:12:40 - ERROR - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:12:40.557238 WHERE submitId='s_20230323053111_20230323043922'
Traceback (most recent call last):
  File "/home/ubuntu/onsite-develop/onsite-test-server/tester/connector.py", line 100, in _db_commit
    cur.execute(script)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 606, in tough_method
    result = method(*args, **kwargs)  # try to execute
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '02:12:40.557238 WHERE submitId='s_20230323053111_20230323043922'' at line 1")
2023-03-25 02:12:43 - INFO  - UPDATE submit SET status='CONTAINER ERROR', score=NULL, resultLink='https://resource.onsite.run/results/2023031901/20230323043922&2023-03-23_17-31-11.zip' WHERE submitId='s_20230323053111_20230323043922'
2023-03-25 02:12:44 - INFO  - UPDATE submit SET status='CONTAINER ERROR', score=NULL, resultLink='https://resource.onsite.run/results/2023031901/20230323044004&2023-03-23_17-32-30.zip' WHERE submitId='s_20230323053230_20230323044004'
2023-03-25 02:14:27 - INFO  - UPDATE submit SET status='SUCCESS', score=67.08266666666667, resultLink='https://resource.onsite.run/results/2023031902/20230323043922&2023-03-23_17-31-20.zip' WHERE submitId='s_20230323053119_20230323043922'
2023-03-25 02:33:44 - INFO  - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:33:44.812626 WHERE submitId='s_20230323053245_20230323044004'
2023-03-25 02:33:44 - ERROR - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:33:44.812626 WHERE submitId='s_20230323053245_20230323044004'
Traceback (most recent call last):
  File "/home/ubuntu/onsite-develop/onsite-test-server/tester/connector.py", line 100, in _db_commit
    cur.execute(script)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 606, in tough_method
    result = method(*args, **kwargs)  # try to execute
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '02:33:44.812626 WHERE submitId='s_20230323053245_20230323044004'' at line 1")
2023-03-25 02:33:49 - INFO  - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:33:49.829854 WHERE submitId='s_20230323053245_20230323044004'
2023-03-25 02:33:49 - ERROR - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:33:49.829854 WHERE submitId='s_20230323053245_20230323044004'
Traceback (most recent call last):
  File "/home/ubuntu/onsite-develop/onsite-test-server/tester/connector.py", line 100, in _db_commit
    cur.execute(script)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 606, in tough_method
    result = method(*args, **kwargs)  # try to execute
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '02:33:49.829854 WHERE submitId='s_20230323053245_20230323044004'' at line 1")
2023-03-25 02:33:51 - INFO  - UPDATE submit SET status='CONTAINER ERROR', score=NULL, resultLink='https://resource.onsite.run/results/2023031903/20230323044004&2023-03-23_17-32-46.zip' WHERE submitId='s_20230323053245_20230323044004'
2023-03-25 02:38:20 - INFO  - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:38:20.755079 WHERE submitId='s_20230323053245_20230323044004'
2023-03-25 02:38:20 - ERROR - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:38:20.755079 WHERE submitId='s_20230323053245_20230323044004'
Traceback (most recent call last):
  File "/home/ubuntu/onsite-develop/onsite-test-server/tester/connector.py", line 100, in _db_commit
    cur.execute(script)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 606, in tough_method
    result = method(*args, **kwargs)  # try to execute
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '02:38:20.755079 WHERE submitId='s_20230323053245_20230323044004'' at line 1")
2023-03-25 02:38:25 - INFO  - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:38:25.772372 WHERE submitId='s_20230323053245_20230323044004'
2023-03-25 02:38:25 - ERROR - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:38:25.772372 WHERE submitId='s_20230323053245_20230323044004'
Traceback (most recent call last):
  File "/home/ubuntu/onsite-develop/onsite-test-server/tester/connector.py", line 100, in _db_commit
    cur.execute(script)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 606, in tough_method
    result = method(*args, **kwargs)  # try to execute
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '02:38:25.772372 WHERE submitId='s_20230323053245_20230323044004'' at line 1")
2023-03-25 02:38:27 - INFO  - UPDATE submit SET status='CONTAINER ERROR', score=NULL, resultLink='https://resource.onsite.run/results/2023031903/20230323044004&2023-03-23_17-32-46.zip' WHERE submitId='s_20230323053245_20230323044004'
2023-03-25 02:40:11 - INFO  - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:40:11.129253 WHERE submitId='s_20230323053245_20230323044004'
2023-03-25 02:40:11 - ERROR - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:40:11.129253 WHERE submitId='s_20230323053245_20230323044004'
Traceback (most recent call last):
  File "/home/ubuntu/onsite-develop/onsite-test-server/tester/connector.py", line 100, in _db_commit
    cur.execute(script)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 606, in tough_method
    result = method(*args, **kwargs)  # try to execute
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '02:40:11.129253 WHERE submitId='s_20230323053245_20230323044004'' at line 1")
2023-03-25 02:40:16 - INFO  - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:40:16.145129 WHERE submitId='s_20230323053245_20230323044004'
2023-03-25 02:40:16 - ERROR - UPDATE submit SET status='TESTING', testTime=2023-03-25 02:40:16.145129 WHERE submitId='s_20230323053245_20230323044004'
Traceback (most recent call last):
  File "/home/ubuntu/onsite-develop/onsite-test-server/tester/connector.py", line 100, in _db_commit
    cur.execute(script)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 606, in tough_method
    result = method(*args, **kwargs)  # try to execute
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '02:40:16.145129 WHERE submitId='s_20230323053245_20230323044004'' at line 1")
2023-03-25 02:40:18 - INFO  - UPDATE submit SET status='CONTAINER ERROR', score=NULL, resultLink='https://resource.onsite.run/results/2023031903/20230323044004&2023-03-23_17-32-46.zip' WHERE submitId='s_20230323053245_20230323044004'
2023-03-25 02:41:14 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-25 02:41:14' WHERE submitId='s_20230323053245_20230323044004'
2023-03-25 02:44:05 - INFO  - UPDATE submit SET status='SUCCESS', score=35.884, resultLink='https://resource.onsite.run/results/2023031903/20230323044004&2023-03-23_17-32-46.zip' WHERE submitId='s_20230323053245_20230323044004'
2023-03-25 02:48:16 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-25 02:48:16' WHERE submitId='s_20230321111758_20230307123639'
2023-03-25 02:48:20 - INFO  - UPDATE submit SET status='PULL ERROR', score=NULL, resultLink='https://resource.onsite.run/results/2023031601/20230307123639&2023-03-21_11-17-58.zip' WHERE submitId='s_20230321111758_20230307123639'
2023-03-25 02:48:21 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-25 02:48:21' WHERE submitId='s_20230321112324_20230307123639'
2023-03-25 02:48:21 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-25 02:48:21' WHERE submitId='s_20230321112647_20230307123639'
2023-03-25 02:48:25 - INFO  - UPDATE submit SET status='PULL ERROR', score=NULL, resultLink='https://resource.onsite.run/results/2023031601/20230307123639&2023-03-21_11-23-24.zip' WHERE submitId='s_20230321112324_20230307123639'
2023-03-25 02:48:26 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-25 02:48:26' WHERE submitId='s_20230321112839_20230307123639'
2023-03-25 02:48:26 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-25 02:48:26' WHERE submitId='s_20230321113222_20230307123639'
2023-03-25 02:48:26 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-25 02:48:26' WHERE submitId='s_20230321113902_20230307123639'
2023-03-25 02:48:31 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-25 02:48:31' WHERE submitId='s_20230321113950_20230307123639'
2023-03-25 02:48:31 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-25 02:48:31' WHERE submitId='s_20230321114003_20230307123639'
2023-03-25 02:48:36 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-25 02:48:36' WHERE submitId='s_20230323053101_20230323043922'
2023-03-25 02:48:36 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-25 02:48:36' WHERE submitId='s_20230322122024_20230307123639'
2023-03-25 02:48:36 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-25 02:48:36' WHERE submitId='s_20230323053111_20230323043922'
2023-03-25 02:48:40 - INFO  - UPDATE submit SET status='PULL ERROR', score=NULL, resultLink='https://resource.onsite.run/results/2023031601/20230307123639&2023-03-22_00-20-25.zip' WHERE submitId='s_20230322122024_20230307123639'
2023-03-25 02:48:41 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-25 02:48:41' WHERE submitId='s_20230323053119_20230323043922'
2023-03-25 02:51:47 - INFO  - UPDATE submit SET status='SUCCESS', score=67.08266666666667, resultLink='https://resource.onsite.run/results/2023031902/20230323043922&2023-03-23_17-31-20.zip' WHERE submitId='s_20230323053119_20230323043922'
2023-03-25 02:52:01 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-25 02:52:01' WHERE submitId='s_20230323053128_20230323043922'
2023-03-25 02:52:11 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-25 02:52:11' WHERE submitId='s_20230323053221_20230323044004'
2023-03-25 02:52:21 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-25 02:52:21' WHERE submitId='s_20230323053230_20230323044004'
2023-03-25 02:52:26 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-25 02:52:26' WHERE submitId='s_20230323053238_20230323044004'
2023-03-25 02:53:02 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-25 02:53:02' WHERE submitId='s_20230323053245_20230323044004'
2023-03-25 02:54:32 - INFO  - UPDATE submit SET status='SUCCESS', score=83.86266666666667, resultLink='https://resource.onsite.run/results/2023031903/20230323043922&2023-03-23_17-31-29.zip' WHERE submitId='s_20230323053128_20230323043922'
2023-03-25 02:57:01 - INFO  - UPDATE submit SET status='SUCCESS', score=31.526666666666664, resultLink='https://resource.onsite.run/results/2023031902/20230323044004&2023-03-23_17-32-38.zip' WHERE submitId='s_20230323053238_20230323044004'
2023-03-25 02:58:22 - INFO  - UPDATE submit SET status='SUCCESS', score=35.884, resultLink='https://resource.onsite.run/results/2023031903/20230323044004&2023-03-23_17-32-46.zip' WHERE submitId='s_20230323053245_20230323044004'
2023-03-25 03:00:16 - INFO  - UPDATE submit SET status='SUCCESS', score=86.7345, resultLink='https://resource.onsite.run/results/2023031901/20230323043922&2023-03-23_17-31-11.zip' WHERE submitId='s_20230323053111_20230323043922'
2023-03-25 03:04:34 - INFO  - UPDATE submit SET status='SUCCESS', score=79.9774, resultLink='https://resource.onsite.run/results/2023031601/20230307123639&2023-03-21_11-39-03.zip' WHERE submitId='s_20230321113902_20230307123639'
2023-03-25 03:05:01 - INFO  - UPDATE submit SET status='SUCCESS', score=79.9774, resultLink='https://resource.onsite.run/results/2023031601/20230307123639&2023-03-21_11-32-23.zip' WHERE submitId='s_20230321113222_20230307123639'
2023-03-25 03:05:26 - INFO  - UPDATE submit SET status='SUCCESS', score=79.9774, resultLink='https://resource.onsite.run/results/2023031601/20230307123639&2023-03-21_11-26-48.zip' WHERE submitId='s_20230321112647_20230307123639'
2023-03-25 03:06:21 - INFO  - UPDATE submit SET status='SUCCESS', score=79.9774, resultLink='https://resource.onsite.run/results/2023031601/20230307123639&2023-03-21_11-28-39.zip' WHERE submitId='s_20230321112839_20230307123639'
2023-03-25 03:06:42 - INFO  - UPDATE submit SET status='SUCCESS', score=79.9774, resultLink='https://resource.onsite.run/results/2023031405/20230323043922&2023-03-23_17-31-01.zip' WHERE submitId='s_20230323053101_20230323043922'
2023-03-25 03:10:27 - INFO  - UPDATE submit SET status='SUCCESS', score=50.301, resultLink='https://resource.onsite.run/results/2023031901/20230323044004&2023-03-23_17-32-30.zip' WHERE submitId='s_20230323053230_20230323044004'
2023-03-25 03:11:39 - INFO  - UPDATE submit SET status='SUCCESS', score=59.48479999999999, resultLink='https://resource.onsite.run/results/2023031601/20230307123639&2023-03-21_11-39-51.zip' WHERE submitId='s_20230321113950_20230307123639'
2023-03-25 03:12:36 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-25 03:12:36' WHERE submitId='s_20230320051500_20230316121333'
2023-03-25 03:16:24 - INFO  - UPDATE submit SET status='SUCCESS', score=40.34360000000001, resultLink='https://resource.onsite.run/results/2023031601/20230307123639&2023-03-21_11-40-03.zip' WHERE submitId='s_20230321114003_20230307123639'
2023-03-25 03:17:29 - INFO  - UPDATE submit SET status='SUCCESS', score=40.34360000000001, resultLink='https://resource.onsite.run/results/2023031405/20230323044004&2023-03-23_17-32-22.zip' WHERE submitId='s_20230323053221_20230323044004'
2023-03-25 03:42:59 - INFO  - UPDATE submit SET status='SUCCESS', score=40.34360000000001, resultLink='https://resource.onsite.run/results/2023031601/20230316121333&2023-03-21_17-15-00.zip' WHERE submitId='s_20230320051500_20230316121333'
2023-03-26 20:14:47 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-26 20:14:47' WHERE submitId='s_20230326081447_20230326024420'
2023-03-26 20:14:47 - INFO  - UPDATE submit SET status='PULL ERROR', score=NULL, resultLink='https://resource.onsite.run/results/2023031903/20230326024420&2023-03-26_20-14-47.zip' WHERE submitId='s_20230326081447_20230326024420'
2023-03-26 20:15:57 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-26 20:15:57' WHERE submitId='s_20230326081556_20230326024420'
2023-03-26 20:16:02 - INFO  - UPDATE submit SET status='IMAGE NOT FOUND', score=NULL, resultLink='https://resource.onsite.run/results/2023031903/20230326024420&2023-03-26_20-15-57.zip' WHERE submitId='s_20230326081556_20230326024420'
2023-03-26 20:18:43 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-26 20:18:43' WHERE submitId='s_20230326081842_20230326024420'
2023-03-26 20:18:47 - INFO  - UPDATE submit SET status='PULL ERROR', score=NULL, resultLink='https://resource.onsite.run/results/2023031903/20230326024420&2023-03-26_20-18-42.zip' WHERE submitId='s_20230326081842_20230326024420'
2023-03-26 20:20:03 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-26 20:20:03' WHERE submitId='s_20230326082000_20230326024420'
2023-03-26 20:20:08 - INFO  - UPDATE submit SET status='IMAGE NOT FOUND', score=NULL, resultLink='https://resource.onsite.run/results/2023031903/20230326024420&2023-03-26_20-20-00.zip' WHERE submitId='s_20230326082000_20230326024420'
2023-03-26 20:32:10 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-26 20:32:10' WHERE submitId='s_20230326083206_20230326024420'
2023-03-26 20:32:16 - INFO  - UPDATE submit SET status='IMAGE NOT FOUND', score=NULL, resultLink='https://resource.onsite.run/results/2023031903/20230326024420&2023-03-26_20-32-06.zip' WHERE submitId='s_20230326083206_20230326024420'
2023-03-26 20:33:06 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-26 20:33:06' WHERE submitId='s_20230326083302_20230326024420'
2023-03-26 20:33:06 - INFO  - UPDATE submit SET status='PULL ERROR', score=NULL, resultLink='https://resource.onsite.run/results/2023031903/20230326024420&2023-03-26_20-33-02.zip' WHERE submitId='s_20230326083302_20230326024420'
2023-03-26 20:36:01 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-26 20:36:01' WHERE submitId='s_20230326083558_20230326024420'
2023-03-26 20:36:01 - INFO  - UPDATE submit SET status='PULL ERROR', score=NULL, resultLink='https://resource.onsite.run/results/2023031903/20230326024420&2023-03-26_20-35-58.zip' WHERE submitId='s_20230326083558_20230326024420'
2023-03-26 20:37:42 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-26 20:37:42' WHERE submitId='s_20230326083740_20230326024420'
2023-03-26 20:39:34 - INFO  - UPDATE submit SET status='SUCCESS', score=83.86266666666667, resultLink='https://resource.onsite.run/results/2023031903/20230326024420&2023-03-26_20-37-41.zip' WHERE submitId='s_20230326083740_20230326024420'
2023-03-27 19:28:26 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-27 19:28:26' WHERE submitId='s_20230327072823_20230322113149'
2023-03-27 19:28:30 - INFO  - UPDATE submit SET status='PULL ERROR', score=NULL, resultLink='https://resource.onsite.run/results/2023031902/20230322113149&2023-03-27_19-28-23.zip' WHERE submitId='s_20230327072823_20230322113149'
2023-03-27 19:29:11 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-27 19:29:11' WHERE submitId='s_20230327072906_20230322113149'
2023-03-27 19:29:15 - INFO  - UPDATE submit SET status='PULL ERROR', score=NULL, resultLink='https://resource.onsite.run/results/2023031902/20230322113149&2023-03-27_19-29-07.zip' WHERE submitId='s_20230327072906_20230322113149'
2023-03-27 19:29:46 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-27 19:29:46' WHERE submitId='s_20230327072942_20230322113149'
2023-03-27 19:31:40 - INFO  - UPDATE submit SET status='SUCCESS', score=67.08266666666667, resultLink='https://resource.onsite.run/results/2023031902/20230322113149&2023-03-27_19-29-43.zip' WHERE submitId='s_20230327072942_20230322113149'
2023-03-28 14:56:05 - ERROR - SELECT userId, userName, school, supervisorName FROM user WHERE 
Traceback (most recent call last):
  File "/home/ubuntu/onsite-develop/onsite-test-server/tester/tools/../connector.py", line 89, in _db_fetch
    cur.execute(script)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 606, in tough_method
    result = method(*args, **kwargs)  # try to execute
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1")
2023-03-28 14:56:11 - ERROR - SELECT userId, userName, school, supervisorName FROM user WHERE 
Traceback (most recent call last):
  File "/home/ubuntu/onsite-develop/onsite-test-server/tester/tools/../connector.py", line 89, in _db_fetch
    cur.execute(script)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 606, in tough_method
    result = method(*args, **kwargs)  # try to execute
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1")
2023-03-28 14:56:39 - ERROR - SELECT userId, userName, school, supervisorName FROM user WHERE 
Traceback (most recent call last):
  File "/home/ubuntu/onsite-develop/onsite-test-server/tester/tools/../connector.py", line 89, in _db_fetch
    cur.execute(script)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 606, in tough_method
    result = method(*args, **kwargs)  # try to execute
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1")
2023-03-28 14:56:58 - ERROR - SELECT userId, userName, school, supervisorName FROM user WHERE 
Traceback (most recent call last):
  File "/home/ubuntu/onsite-develop/onsite-test-server/tester/tools/../connector.py", line 89, in _db_fetch
    cur.execute(script)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/dbutils/steady_db.py", line 606, in tough_method
    result = method(*args, **kwargs)  # try to execute
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/ubuntu/anaconda3/envs/tester/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1")
2023-03-31 20:14:58 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-31 20:14:58' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:14:58 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "WAITING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:14:58 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "RUNNING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:15:50 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-31 20:15:50' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:15:50 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "WAITING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:15:50 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "RUNNING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:15:55 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": ["ERROR"], "cost": [4.869584798812866]}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:19:49 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-31 20:19:49' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:19:49 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "WAITING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:20:36 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-31 20:20:36' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:20:36 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "WAITING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:21:29 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-31 20:21:29' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:21:29 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "WAITING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:22:14 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-31 20:22:14' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:22:14 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "WAITING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:22:26 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-31 20:22:26' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:22:26 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "WAITING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:22:35 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-31 20:22:35' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:22:35 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "WAITING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:22:54 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-31 20:22:54' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:22:54 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "WAITING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:23:31 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-31 20:23:31' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:23:31 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "WAITING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:24:44 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-31 20:24:44' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:24:44 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "WAITING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:25:44 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-31 20:25:44' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:25:44 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "WAITING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:26:25 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-31 20:26:25' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:26:25 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "WAITING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:29:20 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-31 20:29:20' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:29:20 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "WAITING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:30:30 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-31 20:30:30' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:30:30 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "WAITING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:31:09 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-31 20:31:09' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:31:09 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "WAITING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:31:09 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "RUNNING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:31:11 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2275371551513672}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:31:11 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2275371551513672}, "test": {"status": "RUNNING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:31:12 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2275371551513672}, "test": {"status": "ERROR", "cost": 1.531923770904541}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:32:14 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-31 20:32:14' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:32:14 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "WAITING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:32:14 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "RUNNING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:32:15 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2275104522705078}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:32:15 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2275104522705078}, "test": {"status": "RUNNING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 20:33:56 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2275104522705078}, "test": {"status": "SUCCESS", "cost": 100.07386589050293}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 21:09:51 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-31 21:09:51' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 21:09:51 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "WAITING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 21:09:51 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "RUNNING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 21:09:52 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2768182754516602}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 21:09:52 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2768182754516602}, "test": {"status": "RUNNING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 21:11:34 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2768182754516602}, "test": {"status": "SUCCESS", "cost": 102.01330780982971}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 22:43:13 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-31 22:43:13' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 22:43:13 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "WAITING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 22:43:13 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "RUNNING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 22:43:20 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "ERROR", "cost": 6.602899074554443}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 22:43:20 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "ERROR", "cost": 6.602899074554443}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "RUNNING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 22:43:20 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "ERROR", "cost": 6.602899074554443}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "SUCCESS", "cost": 0.09650778770446777}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 22:45:37 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-31 22:45:37' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 22:45:37 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "WAITING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 22:45:37 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "RUNNING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 22:45:38 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2669708728790283}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 22:45:38 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2669708728790283}, "test": {"status": "RUNNING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 22:47:19 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2669708728790283}, "test": {"status": "SUCCESS", "cost": 100.39483118057251}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 22:49:39 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-31 22:49:39' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 22:49:39 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "WAITING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 22:49:39 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "RUNNING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 22:49:40 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.3186304569244385}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 22:49:40 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.3186304569244385}, "test": {"status": "RUNNING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 22:50:07 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.3186304569244385}, "test": {"status": "SUCCESS", "cost": 26.944008350372314}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 22:50:08 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.3186304569244385}, "test": {"status": "SUCCESS", "cost": 26.944008350372314}, "evaluate": {"status": "RUNNING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 22:50:21 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.3186304569244385}, "test": {"status": "SUCCESS", "cost": 26.944008350372314}, "evaluate": {"status": "SUCCESS", "cost": 13.457612752914429}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 22:50:21 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.3186304569244385}, "test": {"status": "SUCCESS", "cost": 26.944008350372314}, "evaluate": {"status": "SUCCESS", "cost": 13.457612752914429}, "upload": {"status": "RUNNING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 22:50:21 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.3186304569244385}, "test": {"status": "SUCCESS", "cost": 26.944008350372314}, "evaluate": {"status": "SUCCESS", "cost": 13.457612752914429}, "upload": {"status": "SUCCESS", "cost": 0.1758439540863037}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 22:54:34 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-31 22:54:34' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 22:54:34 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "WAITING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 22:54:34 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "RUNNING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 22:54:35 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2285199165344238}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 22:54:35 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2285199165344238}, "test": {"status": "RUNNING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 22:55:02 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2285199165344238}, "test": {"status": "SUCCESS", "cost": 26.84421682357788}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 22:55:02 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2285199165344238}, "test": {"status": "SUCCESS", "cost": 26.84421682357788}, "evaluate": {"status": "RUNNING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 22:55:15 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2285199165344238}, "test": {"status": "SUCCESS", "cost": 26.84421682357788}, "evaluate": {"status": "SUCCESS", "cost": 13.270188331604004}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 22:55:15 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2285199165344238}, "test": {"status": "SUCCESS", "cost": 26.84421682357788}, "evaluate": {"status": "SUCCESS", "cost": 13.270188331604004}, "upload": {"status": "RUNNING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 22:55:15 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2285199165344238}, "test": {"status": "SUCCESS", "cost": 26.84421682357788}, "evaluate": {"status": "SUCCESS", "cost": 13.270188331604004}, "upload": {"status": "SUCCESS", "cost": 0.13401317596435547}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 22:55:15 - INFO  - UPDATE submit SET status='SUCCESS', score=93.35333333333334, resultLink='https://resource.onsite.run/results/2023032801/20230307123639&2023-03-31_20-01-28.zip' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:00:40 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-31 23:00:40' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:00:40 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "WAITING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:00:40 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "RUNNING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:02:42 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-31 23:02:42' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:02:42 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "WAITING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:02:42 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "RUNNING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:02:44 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2641663551330566}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:02:44 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2641663551330566}, "test": {"status": "RUNNING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:02:45 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2641663551330566}, "test": {"status": "ERROR", "cost": 1.5252225399017334}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:02:45 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2641663551330566}, "test": {"status": "ERROR", "cost": 1.5252225399017334}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "RUNNING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:02:45 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2641663551330566}, "test": {"status": "ERROR", "cost": 1.5252225399017334}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "SUCCESS", "cost": 0.1380174160003662}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:02:45 - INFO  - UPDATE submit SET status='CONTAINER ERROR', score=NULL, resultLink='https://resource.onsite.run/results/2023032801/20230307123639&2023-03-31_20-01-28.zip' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:03:59 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-31 23:03:59' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:03:59 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "WAITING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:03:59 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "RUNNING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:04:02 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 3.038050413131714}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:04:02 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 3.038050413131714}, "test": {"status": "RUNNING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:04:03 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 3.038050413131714}, "test": {"status": "ERROR", "cost": 1.5271801948547363}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:04:03 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 3.038050413131714}, "test": {"status": "ERROR", "cost": 1.5271801948547363}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "RUNNING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:04:08 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 3.038050413131714}, "test": {"status": "ERROR", "cost": 1.5271801948547363}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "ERROR", "cost": 0.00011515617370605469}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:04:08 - INFO  - UPDATE submit SET status='CONTAINER ERROR', score=NULL, resultLink=NULL WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:04:50 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-31 23:04:50' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:04:50 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "WAITING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:04:50 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "RUNNING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:04:52 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2515230178833008}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:04:52 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2515230178833008}, "test": {"status": "RUNNING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:04:53 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2515230178833008}, "test": {"status": "ERROR", "cost": 1.5421864986419678}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:04:53 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2515230178833008}, "test": {"status": "ERROR", "cost": 1.5421864986419678}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "RUNNING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:04:58 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2515230178833008}, "test": {"status": "ERROR", "cost": 1.5421864986419678}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "ERROR", "cost": 0.00011324882507324219}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:04:58 - INFO  - UPDATE submit SET status='CONTAINER ERROR', score=NULL, resultLink=NULL WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:06:36 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-31 23:06:36' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:06:36 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "WAITING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:06:36 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "RUNNING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:06:38 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2180657386779785}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:06:38 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2180657386779785}, "test": {"status": "RUNNING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:07:05 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2180657386779785}, "test": {"status": "SUCCESS", "cost": 27.61428999900818}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:07:05 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2180657386779785}, "test": {"status": "SUCCESS", "cost": 27.61428999900818}, "evaluate": {"status": "RUNNING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:07:05 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2180657386779785}, "test": {"status": "SUCCESS", "cost": 27.61428999900818}, "evaluate": {"status": "ERROR", "cost": 0.0003504753112792969}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:07:05 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2180657386779785}, "test": {"status": "SUCCESS", "cost": 27.61428999900818}, "evaluate": {"status": "ERROR", "cost": 0.0003504753112792969}, "upload": {"status": "RUNNING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:07:06 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2180657386779785}, "test": {"status": "SUCCESS", "cost": 27.61428999900818}, "evaluate": {"status": "ERROR", "cost": 0.0003504753112792969}, "upload": {"status": "SUCCESS", "cost": 0.13301992416381836}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:08:33 - INFO  - UPDATE submit SET status='TESTING', testTime='2023-03-31 23:08:33' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:08:33 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "WAITING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:08:33 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "RUNNING", "cost": -1}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:08:34 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2513306140899658}, "test": {"status": "WAITING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:08:34 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2513306140899658}, "test": {"status": "RUNNING", "cost": -1}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:09:01 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2513306140899658}, "test": {"status": "SUCCESS", "cost": 26.909855365753174}, "evaluate": {"status": "WAITING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:09:01 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2513306140899658}, "test": {"status": "SUCCESS", "cost": 26.909855365753174}, "evaluate": {"status": "RUNNING", "cost": -1}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:09:15 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2513306140899658}, "test": {"status": "SUCCESS", "cost": 26.909855365753174}, "evaluate": {"status": "SUCCESS", "cost": 13.33405327796936}, "upload": {"status": "WAITING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:09:15 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2513306140899658}, "test": {"status": "SUCCESS", "cost": 26.909855365753174}, "evaluate": {"status": "SUCCESS", "cost": 13.33405327796936}, "upload": {"status": "RUNNING", "cost": -1}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:09:15 - INFO  - UPDATE submit SET testDetail='{"pull": {"status": "SUCCESS", "cost": 1.2513306140899658}, "test": {"status": "SUCCESS", "cost": 26.909855365753174}, "evaluate": {"status": "SUCCESS", "cost": 13.33405327796936}, "upload": {"status": "SUCCESS", "cost": 0.16032743453979492}}' WHERE submitId='s_20230331080127_20230307123639'
2023-03-31 23:09:15 - INFO  - UPDATE submit SET status='SUCCESS', score=93.35333333333334, resultLink='https://resource.onsite.run/results/2023032801/20230307123639&2023-03-31_20-01-28.zip' WHERE submitId='s_20230331080127_20230307123639'
